batch_size: 60
epochs: 150
loss: 'categorical_crossentropy'
log_dir: 'logs/fit/'
architecture:
  n_classes: 84
  n_training_timestep: 30
  n_inference_timestep: 60
  n_activation_units: 64

optimizer:
  learning_rate: 0.01
  beta_1: 0.9
  beta_2: 0.999
  decay: 0.01