data:
  midi_path: data/original_metheny.mid
  offsets:
    - [104, 140]
    - [476, 548]
    - [640, 668]
    - [712, 864]
  sequences_per_offset_interval:
    - 20
    - 10
    - 10
    - 30

train:
  batch_size: 1
  epochs: 150
  loss: categorical_crossentropy

  log_dir: logs/fit/
  weights_dir: src/models/weights/singleLstmLayer_64activations_70samples_1batchSize_fixLastDenseLayer/

  model:
    n_classes: 118
    n_timestep: 30
    n_activation_units: 64

  optimizer:
    learning_rate: 0.01
    decay: 0.01

infer:
  weights: src/models/weights/singleLstmLayer_64activations_70samples_1batchSize/
  batch_size: 1

  model:
    n_classes: 118
    n_timestep: 60
    n_activation_units: 64

notes_vocabulary_path: data/notes_vocabulary.p
chords_vocabulary_path: data/chords_vocabulary.p